# PhantomBans Velocity Configuration
TimeDiff=0
UseMySQL=false

# UpdateChecker: GitHub repository to check for new versions
UpdateChecker.Repository=Hauchdev/PhantomBans

Debug=false
DetailedEnableMessage=true
DetailedDisableMessage=true
Disable Prefix=false
DefaultReason=none
DateFormat=dd.MM.yyyy-HH:mm
LockdownOnError=true
EnableAllPermissionNodes=false
ExemptPlayers=
Log Purge Days=30
MuteCommands=/msg,/tell,/w,/reply,/r,/me,/action

# UUID Fetcher settings
UUID-Fetcher.Dynamic=true
UUID-Fetcher.Enabled=true
UUID-Fetcher.Intern=false
UUID-Fetcher.REST-API.URL=https://api.mojang.com/users/profiles/minecraft/%NAME%?%TIMESTAMP%
UUID-Fetcher.REST-API.Key=id
UUID-Fetcher.BackUp-API.URL=https://api.ashcon.app/mojang/v2/user/%NAME%
UUID-Fetcher.BackUp-API.Key=uuid
