# PhantomBans Velocity MySQL Configuration
MySQL.IP=localhost
MySQL.Port=3306
MySQL.DB-Name=phantombans
MySQL.Username=root
MySQL.Password=password
MySQL.Properties=verifyServerCertificate=false&useSSL=false&useUnicode=true&characterEncoding=utf8
